### ISSUE TITLE
关于RuLyric的一些Bug反馈

### ISSUE THREAD

**Issue by HurtGhostMeow** [BetterNCM/RuLyric#1]
# Bug描述

1. 部分歌曲歌词无法正常滚动，如 _GETCHA!-初音ミク/GUMI/ぎがＰ/KIRA_
2. 桌面歌词没有背景边框，不能很好地进行更改大小，且不会随字体大小变化而变化
3. 桌面歌词没有锁定键，在碰到窗口时不方便

# 复现操作
1. 安装RuLyric插件，并安装依赖插件
2. 播放 _GETCHA!_ 或 _大正浪漫_ ，桌面歌词无法正常显示当前歌曲歌词
3. 调整主歌词和副歌词，桌面歌词的边框并不能自适应更改大小

# 期望行为

1. 能够修复部分歌曲的滚动歌词
2. 能够增加歌词边框自适应或桌面歌词增加背景
3. 能够提供歌词锁定键

# 屏幕截图

![屏幕截图_20230126_234234](https://user-images.githubusercontent.com/56166464/214881395-4bba4f38-bfe4-44bc-bede-d694971b6934.png)

网易云中正在播放 _GETCHA!_ ，但歌词却是 _四有_ 的

![屏幕截图_20230126_234255](https://user-images.githubusercontent.com/56166464/214881724-c9db9b2d-0eee-4bef-9b50-d632f02e136b.png)

# BetterNCM版本

1.0.0

# 网易云音乐版本

2.10.6

# 网易云音乐Patch版本

5ad43a6

# 插件版本

0.1.1

# 补充

on Windows 11 专业版 22623

**Comment by HurtGhostMeow** [comment]
重启、卸载该插件后重新安装仍会出现该问题

插件列表：
![image](https://user-images.githubusercontent.com/56166464/215241676-74596a0d-dc54-4e5b-ac95-cd3f0c8f7db9.png)

**Comment by Whuihuan** [comment]
这里补充一下，歌词发生无法滚动的时候分两种情况，一种是这个issue提到的部分曲子在rulyrics上无法得到lyric造成的
![image](https://user-images.githubusercontent.com/6679148/216487514-42cb1033-8800-4ccf-ac2b-a7340185f535.png)
第二种情况是原先曲目得到了歌词，接下来切一首纯音乐，就会触发，但是这个在betterNCM更新到1.01后，就只剩下上面一种情况
![7~T P%3TRP)F`2GYI6X5DW2](https://user-images.githubusercontent.com/6679148/216488133-7e50df09-a6a4-46d8-b0cc-26bbe21b5896.png)
![KKX@W3GDSGSQ_}6E )AELWW](https://user-images.githubusercontent.com/6679148/216488150-ba7cae1c-8e9f-4471-b11b-1abe2ad5de49.png)
