### ISSUE TITLE
两个小建议/bug(？

### ISSUE THREAD

**Issue by ymy139** [BetterNCM/RuLyric#11]
1.在默认情况下桌面歌词会一直置顶，非常影响正常使用，希望可以添加像雨滴的位置锁定，选择一类的功能
2.每次重启网易云都会移动到默认位置，需要重新移动位置

希望尽快修复，感谢开发！

**Comment by anzheerdiya** [comment]
> 1.在默认情况下桌面歌词会一直置顶，非常影响正常使用，希望可以添加像雨滴的位置锁定，选择一类的功能 2.每次重启网易云都会移动到默认位置，需要重新移动位置
> 
> 希望尽快修复，感谢开发！

确实
