### ISSUE TITLE
歌词位置记忆

### ISSUE THREAD

**Issue by LinJie-mjyb** [BetterNCM/RuLyric#15]
每次重启/重载网易云音乐时状态栏歌词都会回到默认位置，但是默认位置并不适合我，所以能不能添加位置记忆
![image](https://user-images.githubusercontent.com/74543319/224482042-b3f277b8-4231-4326-ad07-7dbb96f68485.png)

**Comment by MicroCBer** [comment]
Completed in 58e5b71e9c365f321d8bd196fa01c7b3163dad29
