### ISSUE TITLE
重启之后歌词没了

### ISSUE THREAD

**Issue by JTFA** [BetterNCM/RuLyric#16]
刚更新0.2.1的时候有歌词，调整了位置，重启之后歌词就不见了

**Comment by MicroCBer** [comment]
删除位置记忆文件 `%AppData%/.betterncm.rulyrics.lastpos.conf`

~~我明明做了防止拖出屏幕外的，奇怪~~

**Comment by JTFA** [comment]
> 删除位置记忆文件 `%AppData%/.betterncm.rulyrics.lastpos.conf`
> 
> ~我明明做了防止拖出屏幕外的，奇怪~

我设置的嵌入任务栏，每重启一次网易云 配置文件里的第二个坐标值都会增加900左右

**Comment by JTFA** [comment]
> 删除位置记忆文件 `%AppData%/.betterncm.rulyrics.lastpos.conf`
> 
> ~我明明做了防止拖出屏幕外的，奇怪~

似乎每次重启网易云之后第二个值都会比之前增加912，所以只有第一次能用，之后重启一次就会跑到屏幕外面，并且重启次数越多离屏幕范围越远（

**Comment by yuexl258** [comment]
请求更新，每次删除缓存太麻烦了
