### ISSUE TITLE
更新到1.1.0后，这个任务栏歌词就不显示了

### ISSUE THREAD

**Issue by SamuraiQAQ** [BetterNCM/RuLyric#17]
![image](https://user-images.githubusercontent.com/62920132/225840013-baf5b699-a219-4c56-9d86-45c559dd8d00.png)
麻烦大佬看下是啥问题

**Comment by SamuraiQAQ** [comment]
对了，我是win10用户，歌曲信息也读取得到，但就是不显示歌词。
![Uploading image.png…]()

**Comment by SamuraiQAQ** [comment]
![image](https://user-images.githubusercontent.com/62920132/225840814-b1b1b20c-e485-4350-8c79-dcea3594a13a.png)

**Comment by woshishabii** [comment]
win11也一样？

**Comment by MicroCBer** [comment]
fixed
