### ISSUE TITLE
重启后位置偏下

### ISSUE THREAD

**Issue by solstice23** [BetterNCM/RuLyric#23]
![image](https://user-images.githubusercontent.com/23134847/226940330-8beb5afd-35ec-4056-abd2-4929037bb3f3.png)

**Comment by limbia** [comment]
同,求修复 每次打开就要手挪下

**Comment by limbia** [comment]
老哥你用的啥字体?我自己装了Circular但插件里没有 用不了a..

**Comment by MicroCBer** [comment]
拖一下高度使其刚好覆盖任务栏

**Comment by solstice23** [comment]
仍然会稍偏下，并且往左移到一个特定的位置
重载前
![image](https://user-images.githubusercontent.com/23134847/229026993-f2204afa-5a9d-4959-94ef-6168841a9cc6.png)
![image](https://user-images.githubusercontent.com/23134847/229027040-8a79a579-2543-4b24-bce5-74488827e345.png)
重载后：
![image](https://user-images.githubusercontent.com/23134847/229027066-0179bc18-2491-4be4-b6b3-c920f6ad4e95.png)
