### ISSUE TITLE
出现报错

### ISSUE THREAD

**Issue by Healock** [BetterNCM/RuLyric#26]
-------- BetterNCM CrashReport -------
BackTrace:

C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 4397(`?w詗咠€?I?w)
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 57AB8(cxxbridge1$rust_vec$str$reserve_total)

--------------------------------------

classname: "Shell_TrayWnd", traywin: 10104

-------- BetterNCM CrashReport -------
BackTrace:

C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1C32A( ?? )
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1CB02( ?? )
C:\betterncm\plugins_runtime\RuLyrics\RuLyrics.dll + 1DDE5(BetterNCMPluginMain)
C:\Program Files (x86)\Netease\CloudMusic\MSIMG32.dll + 6988D(TransparentBlt)
C:\Program Files (x86)\Netease\CloudMusic\cloudmusic.exe + EBE60C(TransparentBlt)
C:\Program Files (x86)\Netease\CloudMusic\cloudmusic.exe + 3A588C3D(TransparentBlt)

--------------------------------------
![](https://user-images.githubusercontent.com/59949582/227787278-991df4a6-77e9-4b73-8efa-5b92c03fea08.png)
BetterNCM 版本
1.0.2

网易云音乐版本
2.10.7

网易云音乐 Patch 版本
db18145

已安装插件
ActionEnhancement-0.1.6
FluentProgressBar-0.2.0
InfLink-0.1.8
LibEAPIRequest-1.6.2
liblyric-1.0.0
list-scroll-fix-0.1.0
LyricBar-0.3.2
PluginMarket
RefinedNowPlaying-2.15.3
relive-theme-0.5.3
RuLyrics-0.3.4
StyleSnippet-0.2.0
VisualRecord-1.0.2
What-is-the-cover-of-this-music-2.0.8

**Comment by DEAN-Cherry** [comment]
同样出现这个问题，似乎对于分辨率过高的显示器不适配？

**Comment by MicroCBer** [comment]
我目前最高在 3k 的显示器上使用过，一切正常，这玩意我没法复现就有点恼火

**Comment by DEAN-Cherry** [comment]
> 我目前最高在 3k 的显示器上使用过，一切正常，这玩意我没法复现就有点恼火

![图片](https://user-images.githubusercontent.com/76607677/230760297-bff7a831-2cc6-437e-979f-8c03ce50cd0f.png)
本次更新后依旧如此，删除后则正常运行

**Comment by Miyo333** [comment]
同样是闪退，我的电脑在之前用得好好的，今天系统突然蓝屏重启以后就不能用了，打开网易云三秒钟直接告知进程崩溃，清除数据、重装网易云和betterncm都试过了还是崩溃，经过试错后发现是这个插件的问题
![image](https://github.com/BetterNCM/RuLyric/assets/58378568/9b220d06-69ae-494f-81f3-4a3a44e21108)
尝试过使用旧版本，直到0.1.4才不会闪退，但是这个版本已经无法使用了，下面是插件列表和版本
![image](https://github.com/BetterNCM/RuLyric/assets/58378568/b7337240-2dd4-49f4-8601-883a8b3b109f)
![image](https://github.com/BetterNCM/RuLyric/assets/58378568/010306c2-3720-4944-a336-17af4dbd1feb)

> 同样出现这个问题，似乎对于分辨率过高的显示器不适配？

我的显示屏是1080p的，并不是高分辨率

**Comment by Miyo333** [comment]
> 尝试删除 %AppData% 下 以.betterncm开头 以.conf结尾的文件

可以使用了
