### ISSUE TITLE
安装RuLyrics后 整个BetterNCM崩溃

### ISSUE THREAD

**Issue by HideUsSaveUs** [BetterNCM/RuLyric#37]
![@Z920XC(NS H OE6`4EB1B2](https://github.com/BetterNCM/RuLyric/assets/39188665/197299f1-2a3b-42c5-8ac4-53e4093c799f)
系统win10

**Comment by MicroCBer** [comment]
临时解决方案：删除 C:\Users\你的用户名\AppData\Roaming\.betterncm.rulyrics.lastpos.conf
