### ISSUE TITLE
安装此插件后网易云无法打开

### ISSUE THREAD

**Issue by JTFA** [BetterNCM/RuLyric#4]

**Comment by anzheerdiya** [comment]
我也是

**Comment by Ling-Zero** [comment]
一样
![image](https://user-images.githubusercontent.com/89287049/216767922-e61f0dd8-4084-4cb4-a860-02febb56c3c8.png)
这是我装的其他插件，不知道哪里冲突

**Comment by JTFA** [comment]
> 一样 ![image](https://user-images.githubusercontent.com/89287049/216767922-e61f0dd8-4084-4cb4-a860-02febb56c3c8.png) 这是我装的其他插件，不知道哪里冲突

把其他插件都卸载了只安装这个也打不开

**Comment by anzheerdiya** [comment]
> 

本来是好的，但我今天更新了一下就打不开了

**Comment by MicroCBer** [comment]
fixed
